batch_size: 512
benchmark_dir: ./experimental_results/SWaT/benchmark_results
best_target_direction: max
best_target_metric: f1
csv_postfix: SWaT_common
d_model: 64
data_root: ./datasets
dataset_id: SWaT
device: 0
entities: all
expid: SWaT
head_num: 3
hyper_num:
- 50
- 30
- 20
inner_size: 5
k: 5
lr: 0.001
metrics:
- f1
- pc
- rc
- acc
- delay
model_id: MSHTran
model_root: ./experimental_results/SWaT/20251207_105825
n_feats: 51
nb_epoch: 20
normalize: minmax
num_workers: 1
point_adjustment:
- true
- false
pool_size_list:
- 2
- 2
result_dir: ./experimental_results
scale_num: 3
seed: 2025
seq_len: 100
stride: 10
test_label_postfix: test_label.pkl
test_postfix: test.pkl
thresholding:
- best
train_label_postfix: train_label.pkl
train_method: train_per_entity
train_postfix: train.pkl
update_rate: 0.3
uptime: '20251207_105825'
valid_ratio: 0
window_direction: backword
window_size: 100
